@hostname = http://localhost:8080

get {{hostname}}/app/

###

get {{hostname}}/api/healthz

###

get {{hostname}}/admin/metrics

###

post {{hostname}}/admin/reset


### validate_chirp - too long
post {{hostname}}/api/chirps
Content-Type: application/json

{
  "body": "Hello kerfuffle world",
  "user_id": "61848fb6-1af4-4daf-ad8b-492bf76837e4"
}


### create user
post {{hostname}}/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###
post {{hostname}}/api/login
Content-Type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}